### ISSUE TITLE
Remove dependency on pelias-config

### ISSUE THREAD

**Issue by dianashk** [pelias/fuzzy-tester#1]
I was never a fan of this coupling to begin with. Now that this is a standalone utility and could later be used with any input data and any geocoder endpoint, having a tight coupling to our config files seems like a bad idea. You should be able to specify a config file from the command line if needed.

**Comment by missinglink** [comment]
Its seems `pelias-config` has become a bind which ties all our otherwise decoupled modules together ;)

I'd agree that if a module is to be considered 'general purpose' it should not contain the word Pelias in the repo at all, on the other hand if it's a Pelias specific module then that's obviously fine.

The npm module is called `pelias-fuzzy-tester` and it's in the `pelias` repo so I'm a little confused as to whether this is intended to be 'general purpose' or not?

**Comment by orangejulius** [comment]
I certainly would love to see this module become completely pelias independent at some point, and once it is, Peter, your guidelines for general purpose vs Pelias specific code is perfect. At this point I'm not too focused on making it general purpose, I'd rather just make it work really well for us, and then once we've proven the value, it will make sense to share it more widely.

I do want to remove the hard dependency on pelias-config sooner rather than later though, and the PR for pelias/esclient#4, combined with the ideas from pelias/esclient#3 basically looks like the right way.

**Comment by dianashk** [comment]
This is no longer a priority. Closing.
