### ISSUE TITLE
Request latency checks

### ISSUE THREAD

**Issue by orangejulius** [pelias/fuzzy-tester#11]
Add checks for each request roundtrip time to not exceed a predetermined threshold. Be able to specify different thresholds for each environment. Report warning if average latency reaches N% of threshold. Report regression if average latency is >= threshold.

From pelias/acceptance-tests#30

**Comment by missinglink** [comment]
this issue is a bit tricky because connections can be intermittent and have inconsistent latency, if we go ahead with this feature it should be informative only, enforcing it as metric which triggers an entire suite failure would result in much fail and `y-u-no!`, especially on dodgy Berlin internet connections.

otherwise we could just use the CPU time reported by elasticsearch, but even then you will get vastly different results; because caches.

**Comment by orangejulius** [comment]
Good point. Real performance testing probably has to be thought about and measured separately from acceptance-tests or any tests for correctness

**Comment by missinglink** [comment]
our current load balancer setup sends `statusCode:408` responses for requests exceeding `3 seconds`, I am happy with this behaviour and the refactor I'm working on should start to record incidences of this (eg. `101 saint mark pl 10009` causes frequent timeouts)

I'd be happy to close this as a `wontfix` as more granular benchmarking at this stage is a bit premature and will likely not be very scientific.

**Comment by missinglink** [comment]
@dianashk you are the original reporter of this issue, are you happy with closing it as `wontfix`?

**Comment by dianashk** [comment]
Yes. I can agree that we should have separate test framework for validating things like latency and load resilience. Closing.
