### ISSUE TITLE
Output query url to pelias.github.io/compare

### ISSUE THREAD

**Issue by tigerlily-he** [pelias/fuzzy-tester#113]
The acceptance tests results return a json string in the results, such as 
```
✔ [1100] "{"venue":"police","address":"1090 N Charlotte Street","locality":"Lancaster","region":"PA"}"
```
In order to run the query in the compare app, all the `"` and `:` must be converted to `&` and `=` to get
```
http://pelias.github.io/compare/#/v1/search/structured%3Fvenue=police&address=1090%20N%20Charlotte%20Street&locality=Lancaster&region=PA
```
A link or even just the `search/structured%3Fvenue=police...` part would speed up testing.

**Comment by orangejulius** [comment]
I think it's safe to consider this fixed by https://github.com/pelias/fuzzy-tester/pull/171, which now outputs the path and parameters for a given query. That text can easily be copied and pasted into the compare app (or anywhere else)
![png](https://user-images.githubusercontent.com/111716/60617555-fb203c00-9da1-11e9-8f97-f4ca9db17d51.png)
